version: '3'
services:
  web:
    build: .
    command: gunicorn Ecommerce.wsgi:application --bind 0.0.0.0:8000
    container_name: web
    expose:
      - 8000
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      - POSTGRES_DB=Ecommerce
      - POSTGRES_USER=jasurbek
      - POSTGRES_PASSWORD=856329471Jas

    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped


  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped


  celery:
    build: .
    command: celery -A Ecommerce worker -l info
    depends_on:
      - web
      - redis
      - db
    restart: unless-stopped

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5555:5555'
    command: 'celery -A Ecommerce flower --address=0.0.0.0'
    depends_on:
      - celery
    restart: unless-stopped


  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_folder:/app/static
    depends_on:
      - web


volumes:
  pgdata:
  static_folder:
